"""Secure Unreal -> ComputerControl bridge.

This module is the only adapter between an UnrealAgent plan and the physical
ComputerControlService. It never creates permission, scope, or approval.
The service remains the authority for policy, scope, checkpoint, coordinate
conversion, driver execution, and audit.
"""
from __future__ import annotations

from dataclasses import dataclass

from app.computer.models import ExecutionMechanism
from app.computer_control.actions import CCActionRequest
from app.computer_control.scopes import CCScope
from app.computer_control.service import CCExecutionResult, ComputerControlService
from app.computer_control.verification import VerificationExpectation, VerificationResult, ComputerVerifier

from .agent import UnrealAgent
from .models import UnrealPlan

@dataclass(frozen=True)
class UnrealBridgeResult:
    """Structured bridge result; no hidden physical authorization."""
    ok: bool
    awaiting_checkpoint: bool = False
    checkpoint_id: str | None = None
    execution: CCExecutionResult | None = None
    error: str | None = None

class UnrealComputerControlBridge:
    """Translate an Unreal plan into the existing CC security boundary.

    ``prepare`` only creates the service checkpoint. ``approve`` is the sole
    bridge method that can reach the physical driver, and it requires the
    exact checkpoint, scope and request generated by ``prepare``.
    """
    def __init__(self, *, service: ComputerControlService, agent: UnrealAgent | None = None, verifier: ComputerVerifier | None = None) -> None:
        self._service = service
        self._agent = agent or UnrealAgent()
        self._verifier = verifier or ComputerVerifier()
        self._prepared: dict[str, tuple[CCScope, CCActionRequest]] = {}

    def prepare(self, *, plan: UnrealPlan, observation_fingerprint: str, scope: CCScope, mechanism: ExecutionMechanism = ExecutionMechanism.COMPUTER_CONTROL) -> UnrealBridgeResult:
        if mechanism is not ExecutionMechanism.COMPUTER_CONTROL:
            return UnrealBridgeResult(False, error="Unreal physical execution requires COMPUTER_CONTROL")
        plan.validate()
        scope.validate()
        action_plan = self._agent.to_action_plan(plan=plan, observation_fingerprint=observation_fingerprint)
        requests = self._agent.resolve_requests(action_plan, mechanism=mechanism)
        if not requests:
            return UnrealBridgeResult(False, error="Unreal plan produced no computer-control requests")
        request = requests[0]
        result = self._service.execute(scope=scope, request=request)
        if result.checkpoint is None:
            return UnrealBridgeResult(result.success, execution=result, error=result.error)
        checkpoint_id = result.checkpoint.id
        self._prepared[checkpoint_id] = (scope, request)
        return UnrealBridgeResult(False, awaiting_checkpoint=True, checkpoint_id=checkpoint_id, execution=result, error=result.error)

    def approve(self, checkpoint_id: str, *, note: str = "") -> UnrealBridgeResult:
        prepared = self._prepared.get(checkpoint_id)
        if prepared is None:
            return UnrealBridgeResult(False, error="unknown or already consumed Unreal checkpoint")
        scope, request = prepared
        result = self._service.approve(checkpoint_id, scope=scope, request=request, note=note)
        self._prepared.pop(checkpoint_id, None)
        return UnrealBridgeResult(result.success, execution=result, error=result.error)

    def refuse(self, checkpoint_id: str, *, note: str = "") -> UnrealBridgeResult:
        prepared = self._prepared.pop(checkpoint_id, None)
        if prepared is None:
            return UnrealBridgeResult(False, error="unknown Unreal checkpoint")
        self._service.refuse(checkpoint_id, note=note)
        return UnrealBridgeResult(False, error="Unreal checkpoint refused")

    def verify(self, *, expectation: VerificationExpectation, found: bool | None = None, focused: bool | None = None, before_fingerprint: str | None = None, after_fingerprint: str | None = None) -> VerificationResult:
        return self._verifier.verify_expectation(expectation=expectation, found=found, focused=focused, before_fingerprint=before_fingerprint, after_fingerprint=after_fingerprint)
